Upgrade RuboCop
zendesk/curlybars pull request #17
Opened 2018-10-02 11:41 UTC by bquorning

2019-07-19 20:40 UTC, bquorning commented
Upgraded RuboCop a whole lot more now…

2020-12-22 10:06 UTC, bquorning commented on spec/curlybars/rendering_support_spec.rb
> -
🤷🏼

2021-01-04 12:18 UTC, vecerek requested changes

2021-01-04 12:18 UTC, vecerek commented on gemfiles/rails5.2.gemfile.lock
> +   2.2.2
@bquorning the CI fails to install the dependencies because of the change in the bundler version. The image should either be updated to use the new bundler or bundle the deps with the older bundler.

2021-01-04 12:46 UTC, bquorning commented on gemfiles/rails5.2.gemfile.lock
> +   2.2.2
Would you be interested in switching to use GitHub Actions instead of CircleCI? #29

2021-01-04 13:10 UTC, vecerek commented on gemfiles/rails5.2.gemfile.lock
> +   2.2.2
That sounds good! I approved it 🙂

2021-01-04 13:17 UTC, vecerek approved these changes
💯 How do we get rid of the obsolete circle CI check?

<img width="434" alt="Screenshot 2021-01-04 at 14 16 57" src="https://user-images.githubusercontent.com/5737996/103539023-98789680-4e97-11eb-8adf-dd22aeeff123.png">

2021-01-04 13:18 UTC, bquorning commented on gemfiles/rails5.2.gemfile.lock
> +   2.2.2
The build is passing now 🎉

2021-01-04 13:20 UTC, bquorning commented
> 💯 How do we get rid of the obsolete circle CI check?

@augustocravosilva Do you have access to https://github.com/zendesk/curlybars/settings/hooks ?

2021-01-04 13:20 UTC, merged

2021-01-04 14:04 UTC, augustocravosilva commented
I've removed the webhook. Hopefully that will stop cicleCI builds